version: "3.9"

services:
  db_postgres:
    image: postgres:14.3-alpine
    # hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db-postgres:/var/lib/postgresql/data
      # - ./scripts/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    network_mode: "host"
    # networks:
    #   - my-net

volumes:
  db-postgres:
    driver: local

networks:
  my-net:
    # external: true
